################################################################Configuration File################################################################
#----------------------------------------------------------------------------------------------------------------------------------------------- #
#
# Config Version: 2.2
# Plugin Version: 4.0
# DO NOT MESS WITH VALUES UNLESS YOU KNOW WHAT YOU'RE DOING
#
# For ALL permission nodes AND more information, visit www.itzilly.com/plugins/sgc
#
#
#
# This toggles the message you receive when someone else updates your gamemode
# This is true by default
# Only allows true / false
targetSendMessage: true